# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7c8b61c4854e826ae80762fb3c9142b68044086ae14db78431ebb8c1630aa874a822ead282f3704eb53adb611d568b95173c919264b557dc1c25a8e7da44865

test:
  secret_key_base: a2eb03a8fe7cbd63c60421572ebf1464ee855006881128764f2096eb1e1590efc045bd2c9aa0fdf95bcd5c7f522b0f71a2eb02e8a8641eeb22163d33e67cd06e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
